language: python
sudo: required
dist: xenial
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
cache: pip
env:
  - PANDAS=specific
  - PANDAS=latest
install:
  - pip install -r requirements.txt
  - if [ $PANDAS = latest ]; then pip install pandas -U; fi
  - pip install codecov
before_script:
- cd StyleFrame/tests/
- chmod +x tests.py
script: coverage run tests.py
notifications:
  email:
    recipients:
      - styleframepy@gmail.com
    on_success: change
    on_failure: always
after_success:
  - codecov
